### ISSUE TITLE
File "box.pt" missing during warm up training

### ISSUE THREAD

**Issue by hjiangav** [syguan96/NeuroFluid#3]
Hello, I tried to do warm up training for renderer using train_renderer.py. I have downloaded the dataset and edited the configuration so that dataset can be correctly found. But after I executed the code, I got the following error:

Traceback (most recent call last):
  File "train_renderer.py", line 18, in <module>
    trainer = Trainer(cfg_warmup)
  File "/home/l7mp/NeuroFluid/trainer/basetrainer.py", line 31, in __init__
    self.init_fn()
  File "/home/l7mp/NeuroFluid/trainer/trainer_renderer.py", line 25, in init_fn
    self.build_dataloader()
  File "/home/l7mp/NeuroFluid/trainer/trainer_renderer.py", line 37, in build_dataloader
    imgscale=self.options.TRAIN.scale, viewnames=self.train_view_names, split='train')
  File "/home/l7mp/NeuroFluid/datasets/dataset.py", line 38, in __init__
    self.read_box()
  File "/home/l7mp/NeuroFluid/datasets/dataset.py", line 123, in read_box
    box_info = joblib.load(osp.join(self.root_dir, bbox_path))
  File "/home/l7mp/anaconda3/envs/fluid-env/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 579, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data_release/watercube/box.pt'

It seems that file 'box.pt' is missing. Did I do something wrong here, or this file has not been released? Thank you for helping!

**Comment by syguan96** [comment]
Opzz ... Thanks for your reminder! You can download it from [here](https://drive.google.com/file/d/1lgJG5aTBxZZAdHOaj64bSUnGusGW6Bzg/view?usp=sharing). 
I will revise this error in the readme tomorrow.

**Comment by hjiangav** [comment]
Thank you for the file, the problem is now solved. By the way, what is the use of 'box.pt'? I notice that it contains huge data.

**Comment by syguan96** [comment]
I save the normal direction and vertices of the container of fluid.
