### ISSUE TITLE
environment issue

### ISSUE THREAD

**Issue by taehoon-yoon** [syguan96/NeuroFluid#8]
Hi, Thanks for your project.
I carefully followed installation guide which you've provided, after that I tried to evaluate Neuro fluid using
`python eval_e2e.py --resume_from $MODEL_PATH --dataset DATASET_NAME`
But I met error like following.
```
Traceback (most recent call last):
  File "/home/taehoon/Desktop/NeuroFluid/tmp.py", line 2, in <module>
    import open3d.ml.torch as ml3d
  File "/home/taehoon/anaconda3/envs/fluid-env/lib/python3.7/site-packages/open3d/ml/torch/__init__.py", line 42, in <module>
    _torch.__version__))
Exception: Version mismatch: Open3D needs PyTorch version 1.12.*, but version 1.13.1+cu116 is installed!
```

It seems like Open3d does not support pytorch version 1.13.1+cu116?
So my question is, can I know your pytorch version used for this project?

Thanks!

**Comment by syguan96** [comment]
Hi, the pytorch wheel we use is downloaded from 
open3d_downloads. See this page: https://github.com/isl-org/open3d_downloads/releases?page=2.

From this issue (https://github.com/isl-org/open3d_downloads/issues/2), it looks like that Open3d has moved to torch_1.12. But I have never tried this.

**Comment by taehoon-yoon** [comment]
Sorry for the late reply. I've managed to solve the environmental issue. 
Anyway I was walking through your code and found out at end2end training step, according to `end2end.yaml`, it seems that
to train end2end it requires `'/data/syguan/fluid_simulation/release/ckpts/trans/transv3_694999.pt'` .
According to your paper, you've used pretrained `Deep Lagrangian Fluid` model, so is `transv3_694999.pt` equal to  [pretrained_model_weights.pt](https://github.com/isl-org/DeepLagrangianFluids/blob/master/scripts/pretrained_model_weights.pt)?

Thanks again!
